//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingRouterBusiness.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametersSent
    {
        public System.Guid WorkerID { get; set; }
        public int ParameterSetID { get; set; }
        public string Result { get; set; }
    
        public virtual ParameterSets ParameterSets { get; set; }
    }
}
