//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genetic
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructionOrder
    {
        public int Sequence { get; set; }
        public long InstructionID { get; set; }
        public long ParameterSetID { get; set; }
    
        public virtual ParameterSets ParameterSets { get; set; }
        public virtual Instructions Instructions { get; set; }
    }
}
